-- Enable extensions
CREATE EXTENSION IF NOT EXISTS unaccent SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA public;

-- Create IMMUTABLE wrapper function for unaccent
CREATE OR REPLACE FUNCTION immutable_unaccent(text)
RETURNS text AS $$
SELECT public.unaccent('public.unaccent', $1);
$$ LANGUAGE sql IMMUTABLE STRICT;

-- ==========================================
-- Tables Creation
-- ==========================================

create table addresses (
    is_default boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    user_id bigint not null,
    phone varchar(15) not null,
    district varchar(100) not null,
    province varchar(100) not null,
    receiver_name varchar(100) not null,
    ward varchar(100) not null,
    detail varchar(255) not null,
    carrier_metadata jsonb,
    primary key (id)
);

create table cart_items (
    quantity integer not null,
    cart_id bigint not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    primary key (id),
    unique (cart_id, product_id)
);

create table carts (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    user_id bigint not null unique,
    primary key (id)
);

create table categories (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    parent_id bigint,
    updated_at timestamp(6),
    name varchar(100) not null,
    slug varchar(120) not null unique,
    image varchar(500),
    primary key (id)
);

create table coupon_applicable_categories (
    category_id bigint,
    coupon_id bigint not null
);

create table coupon_applicable_products (
    coupon_id bigint not null,
    product_id bigint
);

create table coupon_usages (
    discount_applied numeric(12,2) not null,
    coupon_id bigint not null,
    id bigint generated by default as identity,
    order_id bigint not null,
    used_at timestamp(6) not null,
    user_id bigint not null,
    primary key (id)
);

create table coupons (
    is_active boolean not null,
    max_discount_amount numeric(12,2),
    min_order_value numeric(12,2) not null,
    per_user_limit integer not null,
    total_limit integer not null,
    used_count integer not null,
    value numeric(12,2) not null,
    created_at timestamp(6) not null,
    created_by bigint,
    expiry_date timestamp(6) not null,
    id bigint generated by default as identity,
    start_date timestamp(6) not null,
    updated_at timestamp(6),
    type varchar(20) not null check (type in ('PERCENTAGE','FIXED_AMOUNT')),
    code varchar(50) not null unique,
    primary key (id)
);

create table farms (
    is_deleted boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    owner_id bigint not null,
    updated_at timestamp(6),
    status varchar(30) not null check (status in ('PENDING_APPROVAL','ACTIVE','INACTIVE','REJECTED')),
    image_public_id varchar(200),
    name varchar(200) not null,
    location varchar(300),
    certificate varchar(500),
    image_url varchar(500),
    rejection_reason varchar(500),
    description TEXT,
    primary key (id)
);

create table inventory_batches (
    expiry_date date,
    harvest_date date,
    quantity integer not null,
    remaining_quantity integer not null,
    sweetness_level numeric(4,2),
    created_at timestamp(6) not null,
    farm_id bigint,
    id bigint generated by default as identity,
    product_id bigint not null,
    updated_at timestamp(6),
    status varchar(20) not null check (status in ('AVAILABLE','SOLD_OUT','EXPIRED')),
    batch_code varchar(50) not null unique,
    note TEXT,
    primary key (id)
);

create table order_items (
    quantity integer not null,
    subtotal numeric(12,2) not null,
    unit_price numeric(12,2) not null,
    batch_id bigint,
    id bigint generated by default as identity,
    order_id bigint not null,
    product_id bigint not null,
    batch_code varchar(50),
    product_name varchar(200) not null,
    product_thumbnail varchar(500),
    primary key (id)
);

create table orders (
    discount_amount numeric(10,2),
    shipping_fee numeric(10,2) not null,
    subtotal numeric(12,2) not null,
    total_amount numeric(12,2) not null,
    address_id bigint,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    user_id bigint not null,
    payment_method varchar(20) not null check (payment_method in ('COD','VNPAY','MOMO','BANK_TRANSFER')),
    payment_status varchar(20) not null check (payment_status in ('UNPAID','PAID','REFUNDED','FAILED')),
    status varchar(20) not null check (status in ('PENDING','CONFIRMED','PROCESSING','SHIPPING','DELIVERED','CANCELLED','REFUND_REQUESTED','REFUNDED','RETURNED')),
    note varchar(500),
    shipping_address varchar(500),
    primary key (id)
);

create table otp_tokens (
    used boolean not null,
    otp varchar(6) not null,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    type varchar(30) not null check (type in ('PASSWORD_RESET','EMAIL_VERIFICATION')),
    primary key (id)
);

create table payments (
    amount numeric(12,2) not null,
    reconcile_count int default 0 not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    order_id bigint not null unique,
    paid_at timestamp(6),
    updated_at timestamp(6),
    provider varchar(20) not null check (provider in ('COD','VNPAY','MOMO','BANK')),
    status varchar(20) not null check (status in ('UNPAID','PAID','REFUNDED','FAILED')),
    transaction_code varchar(100),
    raw_response TEXT,
    primary key (id)
);

create table product_images (
    sort_order integer,
    id bigint generated by default as identity,
    product_id bigint not null,
    public_id varchar(300),
    image_url varchar(500) not null,
    primary key (id)
);

create table products (
    calories numeric(6,2),
    discount_price numeric(12,2),
    is_organic boolean not null,
    price numeric(12,2) not null,
    weight numeric(8,2),
    category_id bigint,
    created_at timestamp(6) not null,
    created_by bigint,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    status varchar(20) not null check (status in ('ACTIVE','INACTIVE','OUT_OF_STOCK')),
    brand varchar(100),
    origin varchar(100),
    name varchar(200) not null,
    slug varchar(220) not null unique,
    thumbnail_public_id varchar(300),
    thumbnail varchar(500),
    description TEXT,
    primary key (id)
);

create table refresh_tokens (
    expires_at timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    last_used_at timestamp(6) with time zone,
    user_id bigint not null unique,
    token varchar(512) not null unique,
    primary key (id)
);

create table review_images (
    id bigint generated by default as identity,
    review_id bigint not null,
    public_id varchar(300),
    image_url varchar(500) not null,
    primary key (id)
);

create table review_votes (
    is_helpful boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    review_id bigint not null,
    updated_at timestamp(6),
    user_id bigint not null,
    primary key (id),
    constraint uq_review_votes_review_user unique (review_id, user_id)
);

create table reviews (
    helpful_count integer not null,
    is_hidden boolean not null,
    rating integer not null,
    unhelpful_count integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    updated_at timestamp(6),
    user_id bigint not null,
    comment TEXT,
    primary key (id)
);

create table roles (
    id bigint generated by default as identity,
    name varchar(20) not null unique check (name in ('ROLE_USER','ROLE_ADMIN','ROLE_FARMER')),
    primary key (id)
);

create table shipments (
    insurance_fee numeric(10,2),
    shipping_fee numeric(10,2),
    total_fee numeric(10,2),
    cancelled_at timestamp(6),
    created_at timestamp(6) not null,
    created_on_carrier_at timestamp(6),
    expected_delivery_time timestamp(6),
    id bigint generated by default as identity,
    last_sync_at timestamp(6),
    order_id bigint not null unique,
    updated_at timestamp(6),
    carrier_code varchar(30) not null check (carrier_code in ('GHN','GHTK','VIETTEL_POST','J_AND_T','BEST_EXPRESS')),
    current_status varchar(40) not null check (current_status in ('PENDING_PICKUP','PICKING_UP','PICKED_UP','IN_TRANSIT','AT_WAREHOUSE','SORTING','OUT_FOR_DELIVERY','DELIVERY_FAILED','DELIVERED','RETURNING','RETURNED','CANCELLED','EXCEPTION','LOST','DAMAGED','UNKNOWN')),
    client_order_code varchar(100),
    external_order_code varchar(100),
    raw_status varchar(100),
    fail_reason varchar(500),
    carrier_metadata jsonb,
    status_log jsonb,
    primary key (id)
);

create table stock_adjustments (
    adjustment_qty integer not null,
    qty_after integer not null,
    qty_before integer not null,
    adjusted_by bigint,
    batch_id bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    reason varchar(500) not null,
    primary key (id)
);

create table user_roles (
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id)
);

create table users (
    email_verified boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    phone varchar(15),
    provider varchar(20) not null check (provider in ('LOCAL','GOOGLE','FACEBOOK')),
    status varchar(20) not null check (status in ('ACTIVE','INACTIVE','BANNED')),
    email varchar(100) not null unique,
    full_name varchar(100),
    avatar_public_id varchar(300),
    avatar varchar(500),
    password varchar(255),
    provider_id varchar(255),
    primary key (id)
);

create table wishlists (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    updated_at timestamp(6),
    user_id bigint not null,
    primary key (id),
    unique (user_id, product_id)
);

-- ==========================================
-- Indexes Creation
-- ==========================================

create index idx_coupon_usages_coupon_user 
   on coupon_usages (coupon_id, user_id);

create index idx_coupon_usages_order 
   on coupon_usages (order_id);

create index idx_coupons_active_dates 
   on coupons (is_active, start_date, expiry_date);

create index idx_farms_owner 
   on farms (owner_id);

create index idx_farms_status 
   on farms (status);

create index idx_batch_product_status 
   on inventory_batches (product_id, status);

create index idx_batch_expiry 
   on inventory_batches (expiry_date);

create index idx_orders_user_status 
   on orders (user_id, status);

create index idx_orders_status_created 
   on orders (status, created_at desc);

create index idx_orders_payment_method 
   on orders (payment_method);

create index idx_otp_user_type 
   on otp_tokens (user_id, type);

create index idx_products_category 
   on products (category_id);

create index idx_products_status 
   on products (status);

create index idx_refresh_tokens_expires_at 
   on refresh_tokens (expires_at);

create index idx_refresh_tokens_last_used 
   on refresh_tokens (last_used_at);

create index idx_reviews_product 
   on reviews (product_id);

create index idx_reviews_user 
   on reviews (user_id);

create index idx_shipments_order_id 
   on shipments (order_id);

create index idx_shipments_external_code 
   on shipments (external_order_code);

create index idx_shipments_carrier_status 
   on shipments (carrier_code, current_status);

create index idx_stock_adj_batch 
   on stock_adjustments (batch_id);

create index idx_stock_adj_created 
   on stock_adjustments (created_at);

create index idx_users_email 
   on users (email);

create index idx_users_provider_id 
   on users (provider, provider_id);

-- GIN trigram index for searching product names using unaccent
create index idx_products_name_unaccent_trgm 
   on products using gin (immutable_unaccent(lower(name)) gin_trgm_ops);

-- ==========================================
-- Foreign Key Constraints
-- ==========================================

alter table if exists addresses 
   add constraint FK1fa36y2oqhao3wgg2rw1pi459 
   foreign key (user_id) 
   references users;

alter table if exists cart_items 
   add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
   foreign key (cart_id) 
   references carts;

alter table if exists cart_items 
   add constraint FK1re40cjegsfvw58xrkdp6bac6 
   foreign key (product_id) 
   references products;

alter table if exists carts 
   add constraint FKb5o626f86h46m4s7ms6ginnop 
   foreign key (user_id) 
   references users;

alter table if exists categories 
   add constraint FKsaok720gsu4u2wrgbk10b5n8d 
   foreign key (parent_id) 
   references categories;

alter table if exists coupon_applicable_categories 
   add constraint FK6iulmrpitw08078d7rhn0xill 
   foreign key (coupon_id) 
   references coupons;

alter table if exists coupon_applicable_products 
   add constraint FKh7wu7u49aufrv5ri1j65igx25 
   foreign key (coupon_id) 
   references coupons;

alter table if exists coupon_usages 
   add constraint FK3mvslb8gc0ac6501mfmvifgva 
   foreign key (coupon_id) 
   references coupons;

alter table if exists coupon_usages 
   add constraint FKs9yuckyrsqcsgmjsus1unapt4 
   foreign key (order_id) 
   references orders;

alter table if exists coupon_usages 
   add constraint FK6mev6grxbqmt8l0jxvobfg70n 
   foreign key (user_id) 
   references users;

alter table if exists coupons 
   add constraint FK5ta2iuowjf2sx01vtu35oi2an 
   foreign key (created_by) 
   references users;

alter table if exists farms 
   add constraint FKs0bidbivsex2c3d47hs2c8sjl 
   foreign key (owner_id) 
   references users;

alter table if exists inventory_batches 
   add constraint FK926b7y2vv6hyrqc8ct7uh7wxw 
   foreign key (farm_id) 
   references farms;

alter table if exists inventory_batches 
   add constraint FK9wx3rsi5mhamxiuvbqwvgkk9 
   foreign key (product_id) 
   references products;

alter table if exists order_items 
   add constraint FKieex56ece59wda093dx7woids 
   foreign key (batch_id) 
   references inventory_batches;

alter table if exists order_items 
   add constraint FKbioxgbv59vetrxe0ejfubep1w 
   foreign key (order_id) 
   references orders;

alter table if exists order_items 
   add constraint FKocimc7dtr037rh4ls4l95nlfi 
   foreign key (product_id) 
   references products;

alter table if exists orders 
   add constraint FKhlglkvf5i60dv6dn397ethgpt 
   foreign key (address_id) 
   references addresses;

alter table if exists orders 
   add constraint FK32ql8ubntj5uh44ph9659tiih 
   foreign key (user_id) 
   references users;

alter table if exists otp_tokens 
   add constraint FKjyk2kyj8ul2bjqjpentlrpyi1 
   foreign key (user_id) 
   references users;

alter table if exists payments 
   add constraint FK81gagumt0r8y3rmudcgpbk42l 
   foreign key (order_id) 
   references orders;

alter table if exists product_images 
   add constraint FKqnq71xsohugpqwf3c9gxmsuy 
   foreign key (product_id) 
   references products;

alter table if exists products 
   add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
   foreign key (category_id) 
   references categories;

alter table if exists products 
   add constraint FKl0lce8i162ldn9n01t2a6lcix 
   foreign key (created_by) 
   references users;

alter table if exists refresh_tokens 
   add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
   foreign key (user_id) 
   references users;

alter table if exists review_images 
   add constraint FK3aayo5bjciyemf3bvvt987hkr 
   foreign key (review_id) 
   references reviews;

alter table if exists review_votes 
   add constraint FK5bf4o4ap2v7g3qpxt8y28a38x 
   foreign key (review_id) 
   references reviews;

alter table if exists review_votes 
   add constraint FKf48a6afo7lolirjks7uorfaah 
   foreign key (user_id) 
   references users;

alter table if exists reviews 
   add constraint FKpl51cejpw4gy5swfar8br9ngi 
   foreign key (product_id) 
   references products;

alter table if exists reviews 
   add constraint FKcgy7qjc1r99dp117y9en6lxye 
   foreign key (user_id) 
   references users;

alter table if exists shipments 
   add constraint FKrnt4wht95lxxplspltrg9681s 
   foreign key (order_id) 
   references orders;

alter table if exists stock_adjustments 
   add constraint FK9pdsmpi3i001rs2qugj68akny 
   foreign key (adjusted_by) 
   references users;

alter table if exists stock_adjustments 
   add constraint FKbb838dxuhx21v3auu9ih4qk4n 
   foreign key (batch_id) 
   references inventory_batches;

alter table if exists user_roles 
   add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
   foreign key (role_id) 
   references roles;

alter table if exists user_roles 
   add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
   foreign key (user_id) 
   references users;

alter table if exists wishlists 
   add constraint FKl7ao98u2bm8nijc1rv4jobcrx 
   foreign key (product_id) 
   references products;

alter table if exists wishlists 
   add constraint FK330pyw2el06fn5g28ypyljt16 
   foreign key (user_id) 
   references users;
