spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # =========================
  # OAUTH2 CONFIGURATION
  # =========================
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
            client-name: Google

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - public_profile
            client-name: Facebook
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

logging:
  level:
    # Bật log chi tiết (DEBUG/TRACE) cho toàn bộ lõi Spring Security
    org.springframework.security: DEBUG

    # Bật log cho package dự án để theo dõi các filter tùy chỉnh (như JwtAuthFilter)
    backend.pineapple_ecommerce: DEBUG

    # Bật log cho framework web để xem rõ luồng request/response
    org.springframework.web: INFO

app:
  cors:
    allowed-origins: ${FRONTEND_URL}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    secure: true

  # =========================
  # EMAIL BUSINESS CONFIG
  # =========================
  mail:
    from-address: ${MAIL_FROM_ADDRESS}
    from-name: "Pineapple E-commerce"
    base-url: "http://localhost:3000"
    support-email: "support@pineapple.vn"

  vnpay:
    tmn-code: ${VNPAY_TMN_CODE}
    hash-secret: ${VNPAY_HASH_SECRET}
    pay-url: ${VNP_URL}
    return-url: "https://uproar-reference-outrank.ngrok-free.dev/api/v1/payments/vnpay-return"
    ipn-url: "https://uproar-reference-outrank.ngrok-free.dev/api/v1/payments/vnpay-ipn"
    api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
    frontend-result-url: "http://localhost:3000/payment/result"

  ghn:
    token: ${GHN_TOKEN}
    shop-id: ${GHN_SHOP_ID}
    webhook-secret: ${GHN_WEBHOOK_SECRET}
    base-url: https://dev-online-gateway.ghn.vn/shiip/public-api

  # Thêm khi tích hợp GHTK
  # ghtk:
  #   token: ${GHTK_TOKEN}
  #   partner-id: ${GHTK_PARTNER_ID}
  #   base-url: https://services.giaohangtietkiem.vn