spring:
  profiles:
    active: dev

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

  # =========================
  # OAUTH2 CONFIGURATION
  # =========================
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
            client-name: Google

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - public_profile
            client-name: Facebook
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

  # =========================
  # EMAIL CONFIGURATION
  # =========================
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method


logging:
  level:
    # Bật log chi tiết (DEBUG/TRACE) cho toàn bộ lõi Spring Security
    org.springframework.security: DEBUG

    # Bật log cho package dự án để theo dõi các filter tùy chỉnh (như JwtAuthFilter)
    backend.pineapple_ecommerce: DEBUG

    # Bật log cho framework web để xem rõ luồng request/response
    org.springframework.web: INFO